### ISSUE TITLE
Help with Arch installation

### ISSUE THREAD

**Issue by logos88** [brandleesee/ePSXe64Ubuntu#1]
Hello. I know that this has nothing to do with your script, but since you have been dealing with ePSXe in Linux maybe you have any clue about how to solve this problem. If you find it bothering erase the issue please.

When we run epsxe in arch, we get this errors:
```
/opt/epsxe/epsxe: /usr/lib32/libcrypto.so.1.0.0: no version information available (required by /opt/epsxe/epsxe)
/opt/epsxe/epsxe: /usr/lib32/libcurl.so.3: no version information available (required by /opt/epsxe/epsxe)
 * Running ePSXe emulator version 2.0.5. 

(epsxe:21543): Gtk-WARNING **: Content added to the action area of a dialog using header bars

(epsxe:21543): Gtk-WARNING **: Content added to the action area of a dialog using header bars
```
Do you have any clue about how we could solve this?

The installation package is here:
https://aur.archlinux.org/packages/epsxe/

**Comment by brandleesee** [comment]
Hello, on the contrary, I want to help. 
Can you check my answer in this thread, please?
http://ngemu.com/threads/epsxe-2-x-does-not-work-on-fedora-24.189393/
I know it is for fedora but when I had my own problems in Ubuntu on similar issues I delved in knowledge from every Linux source.
You can either reply here or on that particular thread, it's still me!
I'll definitely help any way I can.

**Comment by logos88** [comment]
Thanks for the help. I have tried 
ln -s /usr/lib/libcrypto.so.10 /usr/lib/libcrypto.so.1.0.0
But libcrypto.so.1.0.0 currently exists in the system. So I don't know why it says: no version information available

For libcurl I have tried to install lib32-libcurl-gnutls and libcurl-compat-nostatic but it doesn't solve it.

epsxe looks to work correctly despite the errors so maybe they aren't important.

**Comment by brandleesee** [comment]
I gather this is not an ePSXe-specific problem:
http://unix.stackexchange.com/questions/336997/libcrypto-so-1-0-0-no-version-information-available-required-by-opt-android-s

But, can you check both the answers from this:
http://askubuntu.com/questions/830466/libcrypto-so-1-0-0-no-version-information-available-required-by-ssh

Am I wrong in thinking that those two issues are also related to openssl?
Because it is also referenced here:
http://stackoverflow.com/questions/39789687/libcurl-so-no-version-information-available
Possibly two installs of curl, if that makes sense in relation to ePSXe:
http://serverfault.com/questions/696631/libcurl-so-4-no-version-information-available

I'm pointing you towards other resources because I feel I can better assist in this way.
