### ISSUE TITLE
Port for .ELF

### ISSUE THREAD

**Issue by tryller** [brandleesee/ePSXe64Ubuntu#17]
Can port it for a .ELF executable?
it's very good to play in PS2

**Comment by brandleesee** [comment]
Prefer not to especially since ePSXe is closed-source. I would probably be breaching copyright. 
Personally, I am happy with a script that integrates fully a closed-source piece of software into an Ubuntu install.

Having said so, if anyone wants to do this, why not. So long as I am not implicated in any breach of.
