### ISSUE TITLE
plugins not being recognized

### ISSUE THREAD

**Issue by Fallast** [brandleesee/ePSXe64Ubuntu#28]
i placed tons of plugins into the plugins folder and they don't show up when i go to congig>plugins>video

**Comment by Fallast** [comment]
no it hasn't

**Comment by brandleesee** [comment]
OK, so I'm closing the issue.

But am leaving some links you might find useful.

Also, last comment, generally I do not recommend using any plugins because ePSXe is already an old piece of software and compatible plugins are either very old or too new.

http://pbernert.com/html/gpu.htm

http://pbernert.com/html/spu.htm

https://emulation.gametechwiki.com/index.php/Recommended_PS1_Plugins

https://www.ngemu.com/threads/epsxe-configuration-guide-ubuntu-linux.93374/

**Comment by brandleesee** [comment]
https://www.youtube.com/watch?v=Ru49bfyXijw

My earlier comment with links is misleading.

Plugins simply do not work.
