### ISSUE TITLE
ePSXe not running on linux

### ISSUE THREAD

**Issue by hayderctee** [brandleesee/ePSXe64Ubuntu#3]
Hi 
I just install ePSXe on debian 9 following the installation steps and i got this message when i try to open the emulator :
```
$ ./ePSXe
./ePSXe: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

```

**Comment by hayderctee** [comment]
It's work fine after downloading  `libssl1.0.0.deb` file from [here](https://packages.debian.org/jessie-backports/libssl1.0.0) 
i thing you should add this package to installation script because it's not available in the official repos.
thank you for your work and for retrieving the childhood memories. :+1:

**Comment by brandleesee** [comment]
Yes, my intention is to update the script to accommodate Debian.
In order to do so, I need some info (as I do not have/use Debian).

Can you give me the output of 
**lsb_release -i**
in terminal?

This is just testing as I need to devise a way for the script to differentiate first between Ubuntu and Debian and then between the Ubuntu flavours.

Furthermore, the above result should also coincide with your desktop environment, too.

**Comment by brandleesee** [comment]
The following is for my own information:

On running on Ubuntu 18.04 the following:

`sudo apt install libssl1.0.0`

I get

> libssl1.0.0 is already the newest version (1.0.2n-1ubuntu5)

**Comment by brandleesee** [comment]
To accommodate Debian users I have added that library.
https://github.com/brandleesee/ePSXe64Ubuntu/commit/b3302c11580bfa2fbe16e21a85732d4175723315
Closing unless other reports on this issue are submitted.
