### ISSUE TITLE
My php7.2-curl get removed after install this

### ISSUE THREAD

**Issue by suphm** [brandleesee/ePSXe64Ubuntu#4]

**Comment by brandleesee** [comment]
Can you look into this and report back?
https://stackoverflow.com/a/50242304

**Comment by brandleesee** [comment]
Also to note that ePSXe Linux requires libcurl3 not libcurl4.

**Comment by brandleesee** [comment]
Having said so, you may want to look into this:
http://ngemu.com/threads/ubuntu-bionic-libcurl-so-4-curl_openssl_3-not-found.204577/
However, it is not in mainstream usage which is why it is not called and used in my script.

Also, shall close this issue because the problem lies in the lack of updates and modernization from the developers of ePXEe.

**Comment by brandleesee** [comment]
@suphm please note that recent versions should have fixed your issue.
If negative, please post back.
